version: "3.9"
services:
  aws-localstack:
    image: localstack/localstack:2.0.0
    environment:
      - SERVICES=dynamodb,lambda,apigateway,ssm
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../../tmp/localstack:/var/lib/localstack"
    networks:
      - "local"

  grafana-loki:
    image: grafana/loki:main-3941767
    ports:
      - "3100:3100"
    volumes:
      - "../../tmp/loki:/loki"
    networks:
      - "local"

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    volumes:
      - "../../tmp/grafana:/var/lib/grafana"
    networks:
      - "local"

  mongodb:
    image: mongo:6.0-jammy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: labset
      MONGO_INITDB_ROOT_PASSWORD: labset
    volumes:
      - "../../tmp/mongodb:/data/db"
    networks:
      - "local"

  mongodb-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: labset
      ME_CONFIG_MONGODB_ADMINPASSWORD: labset
      ME_CONFIG_MONGODB_URL: mongodb://labset:labset@mongodb:27017/
    networks:
      - "local"

networks:
  local:
    driver: "bridge"
